# Generated by Django 4.0.3 on 2024-08-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_enrol',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
