# Generated by Django 4.0.3 on 2024-08-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0002_employee_enrol_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_enrol',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
